### version vpp
GET {{host}}/vpp/version

### list all interfaces
GET {{host}}/interfaces/

### create loopback
POST {{host}}/interfaces/loopback
Content-Type: application/json

{}

### set interface admin state
POST {{host}}/interfaces/1/state
Content-Type: application/json

{
  "admin_up": true
}

### delete loopback interface
DELETE {{host}}/interfaces/1

### add ip adress interface
POST {{host}}/interfaces/1/ip
Content-Type: application/json

{
  "address": "10.0.0.1",
  "prefix": 24
}