### version vpp
GET {{host}}/vpp/version

### list all interfaces
GET {{host}}/interfaces/

### create loopback
POST {{host}}/interfaces/loopback
Content-Type: application/json

{}

### set interface admin state
POST {{host}}/interfaces/2/state
Content-Type: application/json

{
  "admin_up": true
}