### version vpp
GET {{host}}/vpp/version

### list all interfaces
GET {{host}}/interfaces/

### create loopback 1
POST {{host}}/interfaces/loopback
Content-Type: application/json

{}

### create loopback 2
POST {{host}}/interfaces/loopback
Content-Type: application/json

{}

### set interface admin state
POST {{host}}/interfaces/1/state
Content-Type: application/json

{
  "admin_up": true
}

### set interface admin state
POST {{host}}/interfaces/2/state
Content-Type: application/json

{
  "admin_up": true
}

### add ip adress interface 1
POST {{host}}/interfaces/1/ip
Content-Type: application/json

{
  "address": "10.0.0.2",
  "prefix": 24
}

### add ip adress interface 2
POST {{host}}/interfaces/2/ip
Content-Type: application/json

{
  "address": "192.168.1.1",
  "prefix": 24
}

### create vrf
POST {{host}}/vrf
Content-Type: application/json

{
  "id": 1,
  "name": "vrf-1"
}

### add route 1
POST {{host}}/routes
Content-Type: application/json

{
  "destination": "0.0.0.0/0",
  "vrf": 1,
  "next_hops": [
    {
      "ip": "10.0.0.2",
      "if_index": 1,
      "weight": 1,
      "drop": false
    }
  ]
}

### add route 2
POST {{host}}/routes
Content-Type: application/json

{
  "destination": "100.1.1.0/24",
  "vrf": 1,
  "next_hops": [
    {
      "ip": "192.168.1.1",
      "if_index": 2,
      "weight": 1,
      "drop": false
    }
  ]
}

### get list routes
GET {{host}}/routes?vrf=1

### get routes
GET  {{host}}/routes/1?prefix=0.0.0.0/0

### get list vrf
GET {{host}}/vrf

### create acl
POST {{host}}/acl
Content-Type: application/json

{
  "name": "example-acl",
  "rules": [
    {
      "action": 1,
      "proto": 6,
      "src": {"address": "10.0.0.0", "prefix": 24},
      "dst": {"address": "10.0.0.10", "prefix": 32},
      "src_port_low": 0,
      "src_port_high": 65535,
      "dst_port_low": 443,
      "dst_port_high": 443,
      "tcp_flags_mask": 0,
      "tcp_flags_value": 0
    },
    {
      "action": 0,
      "proto": 6,
      "src": {"address": "10.0.1.0", "prefix": 24},
      "dst": {"address": "10.0.0.10", "prefix": 32},
      "src_port_low": 0,
      "src_port_high": 65535,
      "dst_port_low": 22,
      "dst_port_high": 22,
      "tcp_flags_mask": 0,
      "tcp_flags_value": 0
    }
  ]
}

### create acl ip6
POST {{host}}/acl
Content-Type: application/json

{
  "name": "example-acl-ip6",
  "rules": [
    {
      "action": 1,
      "proto": 6,
      "src": {"address": "2001:db8:1::", "prefix": 64},
      "dst": {"address": "2001:db8:2::10", "prefix": 128},
      "dst_port_low": 443,
      "dst_port_high": 443
    }
  ]
}

### update acl 1
PUT {{host}}/acl/1
Content-Type: application/json

{
  "rules": [
    {
      "action": 1,
      "proto": 6,
      "src": {"address": "10.0.0.0", "prefix": 24},
      "dst": {"address": "10.0.0.10", "prefix": 32},
      "src_port_low": 0,
      "src_port_high": 65535,
      "dst_port_low": 443,
      "dst_port_high": 443,
      "tcp_flags_mask": 0,
      "tcp_flags_value": 0
    }
  ]
}

### get list acls
GET {{host}}/acl

### get list acls for interface 1
GET {{host}}/interfaces/1/acl

### attach acl 0 interface 1
POST {{host}}/interfaces/1/acl
Content-Type: application/json

{
  "acl_id": 0,
  "direction": 1
}

### attach acl 1 interface 2
POST {{host}}/interfaces/2/acl
Content-Type: application/json

{
  "acl_id": 1,
  "direction": 0
}

### detach acl 0 interface 1
DELETE {{host}}/interfaces/1/acl
Content-Type: application/json

{
  "acl_id": 0,
  "direction": 1
}

### detach acl 1 interface 2
DELETE {{host}}/interfaces/2/acl
Content-Type: application/json

{
  "acl_id": 1,
  "direction": 0
}

### delete route 1
DELETE {{host}}/routes
Content-Type: application/json

{
  "destination": "0.0.0.0/0",
  "vrf": 1,
  "next_hops": [
    {
      "ip": "10.0.0.2",
      "if_index": 1,
      "weight": 1,
      "drop": false
    }
  ]
}

### delete route 2
DELETE {{host}}/routes
Content-Type: application/json

{
  "destination": "100.1.1.0/24",
  "vrf": 1,
  "next_hops": [
    {
      "ip": "192.168.1.1",
      "if_index": 2,
      "weight": 1,
      "drop": false
    }
  ]
}

### delete acl 0
DELETE {{host}}/acl/0

### delete acl 1
DELETE {{host}}/acl/1

### delete vfr 1
DELETE {{host}}/vrf/1

### delete loopback interface 1
DELETE {{host}}/interfaces/1

### delete loopback interface 2
DELETE {{host}}/interfaces/2